server:
  port: 8002
spring:
  application:
    name: openfeign-client
#服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
logging:
  level:
    org.springframework.cloud.gateway: debug