spring:
  cloud:
    gateway:
      routes:
        - id: load-balanced-service
          uri: lb://SERVICE-HI
          predicates:
          - Path=/robin/**
          filters:
          - StripPrefix=1
        - id: openfeign-client
          uri: lb://openfeign-client
          predicates:
          - Path=/openfeign-client/**
          filters:
          - StripPrefix=1
        - id: openfeign-consumer
          uri: lb://openfeign-consumer
          predicates:
          - Path=/openfeign-consumer/**
          filters:
          - StripPrefix=1

#关闭eureka的服务注册与发现
ribbon:
  eureka:
    enabled: true 

openfeign-client:
  ribbon:
    # 负载地址
    #listOfServers: http://localhost:8001, http://localhost:8002
    # 负载轮询策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 健康检查
    NFLoadBalancerPingClassName: com.dwring.application.config.HealthCheck